image: ghcr.io/siemens/kas/kas:3.2.3

variables:
  KAS_REPO_REF_DIR: $CI_BUILDS_DIR/persist/repos

stages:
  - prep
  - build
  - post

# One include for each stage of the CI
include:
  - 'ci/prep.yml'
  - 'ci/build.yml'
  - 'ci/post.yml'
